- name: test my new module
  hosts: localhost
  tasks:
  - name: Remove a subnet to keyvault firewall
    azure_rm_keyvault_firewall:
      azure_auth: "Authorization: Bearer xxxxx"
      keyvault_id: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults/{vaultName}'
      subnet_id: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{vnetName}/subnets/{subnetName}'
      state: present
    register: result
  - name: debug
    debug:
      msg: "{{ result }}"